### ISSUE TITLE
Slow HTTP Requests Causes App To Bottleneck

### ISSUE THREAD

**Issue by dylancopeland** [swiftype/swiftype-rb#16]
Hello,

I've noticed an issue with the Swiftype gem that causes a Rails app to greatly slowdown. Requests from an application to Swiftype never seem to timeout. We recently experienced an issue where requests were taking multiple seconds to complete and due to the throughput of requests our Rails app was backed up. The majority of the application processes were hung up waiting for a response from Swiftype causing other non-search related requests to be queued and backed up.

It would be great if there was a timeout option for the Swiftype gem to prevent this from happening.

Thanks for your time.

**Comment by look** [comment]
@dylancopeland there are two things you can do to help with this.

First, specify the `:open_timeout` parameter when you create the `Swiftype::Client` instance. https://github.com/swiftype/swiftype-rb/blob/master/lib/swiftype/client.rb#L20-L21

Second, you can switch to our [asynchronous API](https://swiftype.com/documentation/asynchronous_indexing) which does not wait for the records to be created or updated in the backend before returning (they are enqueued and processed later). This is supported in the client via the [index_documents method](https://github.com/swiftype/swiftype-rb/blob/master/lib/swiftype/client.rb#L336-L367) and [async_create_or_update_documents](https://github.com/swiftype/swiftype-rb/blob/master/lib/swiftype/client.rb#L323-L325) for the low level API. If you use index_documents, make sure you use `:poll => false` so it won't repeatedly check the creation status.

**Comment by dylancopeland** [comment]
Hey @look, aside from the `:open_timeout` is there any other way to specify a timeout just while searching? Even after giving the `Swiftype::Client` a timeout of 2 we're seeing some slow requests in production that are taking over 2 seconds.

**Comment by dylancopeland** [comment]
This is still happening. Any other possible solutions?

**Comment by qhoxie** [comment]
Hi Dylan,

We have something prepared internally that just hasn't yet been released.  I'll do my best to push it through in the next day or so.  Apologies for the delay.

Best,
Quin

**Comment by qhoxie** [comment]
@dylancopeland Here you go.  If you update to the latest version, you can use the overall_timeout option to accomplish this:  http://www.rubydoc.info/github/swiftype/swiftype-rb/master/Swiftype/Client#configure-class_method

**Comment by dylancopeland** [comment]
Awesome, I'll give this a shot. Thank you @qhoxie!

**Comment by dylancopeland** [comment]
Hey @qhoxie, was the gem with the overall_timeout option ever released? It looks like 1.2.0 is the latest gem and the Swiftype client doesn't contain that option.

Thanks.

**Comment by qhoxie** [comment]
Hi @dylancopeland It hasn't yet been pushed as a full release yet but we do have people using it by pointing their Gemfile to the latest git ref.  We'll push a release soon.

**Comment by dylancopeland** [comment]
Ah gotcha, thanks for the clarification!

**Comment by klarrimore** [comment]
you probably already know this but you can also build it yourself like this
```
git clone git@github.com:swiftype/swiftype-rb.git
cd ./swiftype-rb
gem build swiftype.gemspec
```

**Comment by dylancopeland** [comment]
Hey @klarrimore, thanks for those instructions. I think I'm just going to hold off until 1.2.1 is officially released so there aren't any unwanted surprises in production. :smile:

**Comment by look** [comment]
@dylancopeland can you give version 1.2.1 a try? Thanks!

**Comment by dylancopeland** [comment]
Hey @look,

We updated to 1.2.1 last night but the problem seems to still be there. Earlier this morning some requests were taking up to 10 seconds to complete. This is a serious issue that has been going on for close to a year now. Is there anything we can do on our end to mitigate it?

Thanks.
