### ISSUE TITLE
Index single document

### ISSUE THREAD

**Issue by pyromaniackeca** [swiftype/swiftype-rb#17]
Just wanted to let you guys know that the code provided in the readme for creating a single document doesn't work(at least for me). When using:

`client.index_documents("engine_slug", "document_type", single_document_params_hash)`

I would get an internal server error response, while when switching to:

`client.index_documents("engine_slug", "document_type", [single_document_params_hash])`

Everything works as expected. I'm not sure if this is a documentation issue or a bug.

**Comment by look** [comment]
Thanks for bringing this to our attention. Looking at the code, it seems the documentation is wrong. However, there's not reason it couldn't support both calling styles. I'll discuss with the team.

**Comment by look** [comment]
Actually, can you send us a complete example? (You can email support@swiftype.com if it's not OK to post here.)

The code [already converts the parameter to an Array](https://github.com/swiftype/swiftype-rb/blob/master/lib/swiftype/client.rb#L351) so your two examples should be equivalent.

**Comment by pyromaniackeca** [comment]
I have taken a look at the code myself at one point, but forgot to mention it when posting. It does seem like it should be working for both examples. I will try and send you a hello world app as soon as I am able.
