### ISSUE TITLE
Proxy URL Support

### ISSUE THREAD

**Issue by drcapulet** [swiftype/swiftype-rb#28]
The current code relies on Net::HTTP's default logic of using `ENV['http_proxy']` to determine the proxy (if any) to use. Unfortunately, setting a global proxy is unpredictable (even when using `ENV['no_proxy']`) across different Ruby HTTP clients - we prefer to explicit set the proxy for the connections that need it. Could y'all look into adding first-class support for configuring a proxy URL?

**Comment by JasonStoltz** [comment]
Hey @drcapulet, I think that sounds reasonable. We can certainly look into that.

**Comment by JasonStoltz** [comment]
Hey @drcapulet. I have this PR open to add proxy support. Can you give this a glance and make sure this satisfies your use case? https://github.com/swiftype/swiftype-rb/pull/29
